"""Create institutions table

Revision ID: 280889419066
Revises: 984ae7ff90cd
Create Date: 2026-07-16 21:14:04.348629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '280889419066'
down_revision: Union[str, Sequence[str], None] = '984ae7ff90cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('email_to', sa.String(length=255), nullable=False))
    op.add_column('institutions', sa.Column('email_cc', sa.String(length=255), nullable=True))
    op.drop_column('institutions', 'cc')
    op.drop_column('institutions', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('institutions', sa.Column('cc', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('institutions', 'email_cc')
    op.drop_column('institutions', 'email_to')
    # ### end Alembic commands ###
