"""Create institutions table

Revision ID: e237c47e4613
Revises: 280889419066
Create Date: 2026-07-16 22:06:18.476030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e237c47e4613'
down_revision: Union[str, Sequence[str], None] = '280889419066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('bank_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_institutions_bank_id'), 'institutions', ['bank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutions_bank_id'), table_name='institutions')
    op.drop_column('institutions', 'bank_id')
    # ### end Alembic commands ###
